sonar.projectKey=SuriyaBoon_SentinelGRC
sonar.organization=suriyaboon
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=test_*.py
sonar.tests=.
sonar.test.inclusions=test_*.py
